#!/bin/bash
echo $(($(echo "$WATER" | tr 'water' '01234' | awk '{s=0 for(i=1;i<=length;i++)s=s*5+substr($0,i,1)}END{print s}') + $(echo "$STIR" | tr 'stir' '0123' | awk '{s=0 for(i=1;i<=length;i++)s=s*4+substr($0,i,1)}END{print s}'))) | awk '{s="bestchol" r="" do{r=substr(s,($1%10)+1,1)r $1=int($1/10)}while($1>0) print r}'
