#!/bin/bash
tr water 01234 <<< "$WATER" | xargs -I@ bash -c 'w=@; tr stir. 01234 <<< "$STIR" | xargs -I@ bash -c '"'"'s=@; n=$((w + s)) && b=bestchol && printf "%o" $n | fold -w1 | while read -r d; do printf "%s" "${b:$d:1}"; done || echo b'"'"''
